version: '3'
services:
  app:
    image: sulaplink001/go-hello-world:latest
    container_name: go-hello-world
    restart: always
    ports:
      - 5000:5000
  app-dev:
    image: sulaplink001/go-hello-world:dev-VERSION
    container_name: go-hello-world_DEV
    restart: always
    ports:
      - 5001:5000
